name: 'Code QA'


on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
      
      
permissions:
  contents: read


jobs:sen de 12 en 27 jaar een profiel met hun skills a
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-format
        
      - name: Run linter
        run: |
          clang-format --dry-run --Werror --style=file:.clang-format src/*c src/*.h
