name: 'Code QA'


on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
      
      
permissions:
  contents: read


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      
      - name: Dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-format
          
      - name: Lint
        run: |
          clang-format --dry-run --Werror src/*.c src/*.h
