name: 'Docs'


on:
  push:
    branches:
      - 'main'
  pull_request:  # Remove this before merge
    types:
      - opened
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
        with:
          # GitHub token
          token: ${{ github.token }}
